[ ! -z "$PS1" ] || exit

source /opt/conda/etc/profile.d/conda.sh
conda activate neuroimaging

source /etc/fsl/fsl.sh

export PATH=$PATH:/opt/niftyreg/bin:/opt/smt-0.4-linux-x64/bin

export TRACTOR_HOME=/opt/tractor
export PATH=$PATH:$TRACTOR_HOME/bin
export MANPATH=$MANPATH:$TRACTOR_HOME/share/man

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(R RHOME)/lib
